"""add reply authors

Revision ID: 6656ccda2ae6
Revises: 3d8251495145
Create Date: 2026-09-15 02:04:11.206679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6656ccda2ae6'
down_revision: Union[str, Sequence[str], None] = '3d8251495145'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('replies', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_replies_author_id'), 'replies', ['author_id'], unique=False)
    op.create_foreign_key(None, 'replies', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'replies', type_='foreignkey')
    op.drop_index(op.f('ix_replies_author_id'), table_name='replies')
    op.drop_column('replies', 'author_id')
    # ### end Alembic commands ###
